# Generated by Django 4.2.7 on 2025-06-28 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default=999, max_length=50),
            preserve_default=False,
        ),
    ]
