# Generated by Django 5.1.7 on 2025-08-28 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('message', models.TextField(verbose_name='Diganos lo que se le cante')),
                ('color', models.CharField(max_length=30, verbose_name='Su color favorito...')),
                ('fruit', models.CharField(max_length=30, verbose_name='Su fruta favorita...')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
